Name: ci-cd

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Testing code:
    runs on: ubuntu-latest
  steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: setup node
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: "npm"

    - name: install dependencies
      run: npm ci

    - name: Run test
      run: npm test

    - name: test run docker build
      run: |
        docker build -t test-build .

        echo "docker build successful"
